services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fcg.gameservice.api:latest
    container_name: FCGGameService-api
    restart: unless-stopped
    ports:
      - "5000:8080"   # HTTP
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_HTTP_PORT: 8080
      ASPNETCORE_ENVIRONMENT: "Development"
      MongoDbSettings__ConnectionString: "mongodb://localhost:27017"
      MongoDbSettings__DatabaseName: "FCGGameService"
      ElasticSettings__ApiKey: "TVRoMTRwZ0JIQ3pxMjNvNXlzS2o6OUYzRWpXQmFhRnk0cWg2cmg2b3NiQQ=="
      ElasticSettings__CloudId: "My_deployment:ZWFzdHVzMi5henVyZS5lbGFzdGljLWNsb3VkLmNvbTo0NDMkMzQzODAwOWU3NmZkNDE2ZjgyMTE1MTQ4NjM5OWJhOWMkYjY1MjM0YTk4NDRmNDc4OGFlMjcxZWUzYTc4NTNmNzc="
      AzureStorage__ConnectionString: "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=stfcgpayments;AccountKey=XMVTiBBhW72Zi5DuaWMdjMPvO+BB6+eI9vcCXeI0WpUA+7dGQKYjiduistttaL7ZRF2YNrjJQ0oo+AStZekCfw==;BlobEndpoint=https://stfcgpayments.blob.core.windows.net/;FileEndpoint=https://stfcgpayments.file.core.windows.net/;QueueEndpoint=https://stfcgpayments.queue.core.windows.net/;TableEndpoint=https://stfcgpayments.table.core.windows.net/"
      AzureStorage__ProducerQueueName: "game-purchase-requested"
      AzureStorage__ConsumerQueueName: "game-purchase-completed"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health", "||", "curl", "-f", "http://localhost:8080/", "||", "exit", "1"]
      interval: 45s
      timeout: 15s
      retries: 10
      start_period: 90s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - fcg_network

networks:
  fcg_network:
    driver: bridge