services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fcggameservice-api
    container_name: FCGGameService-api
    restart: unless-stopped
    ports:
      - "5000:5000"   # HTTP
      - "5001:5001"   # HTTPS
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
      ASPNETCORE_URLS: "http://+:5000;https://+:5001"
      ASPNETCORE_ENVIRONMENT: "Development"
      MongoDbSettings__ConnectionString: ""
      MongoDbSettings__DatabaseName: ""
      ElasticSettings__ApiKey: ""
      ElasticSettings__CloudId: ""
      AzureStorage__ConnectionString: ""
      AzureStorage__ProducerQueueName: ""
      AzureStorage__ConsumerQueueName: ""
    healthcheck:
      test: ["CMD-SHELL", "curl -f -sS http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - fcg_network

networks:
  fcg_network:
    driver: bridge